#########################################
# Aurora MySQL Configuration
#########################################
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=update

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

#########################################
# ElastiCache (Redis) Configuration
#########################################
spring.cache.type=redis
# spring.redis.host=${REDIS_HOST:redis-cluster.example.com}
spring.redis.host=client-profile-cache-prod-ofbtg1.serverless.apse1.cache.amazonaws.com
# spring.redis.port=${REDIS_PORT:6379}
spring.redis.port=6379
# spring.redis.password=${REDIS_PASSWORD:}
spring.redis.password=
spring.redis.timeout=2000ms
spring.redis.ssl=true

# Connection pool
spring.redis.lettuce.pool.max-active=20
spring.redis.lettuce.pool.max-idle=10
spring.redis.lettuce.pool.min-idle=2
spring.redis.lettuce.pool.max-wait=2000ms
spring.redis.lettuce.shutdown-timeout=100ms

# Cache TTL
cache.default.ttl=600

#########################################
# Logging (reduced verbosity)
#########################################
logging.level.com.example.client=INFO
aws.sns.topic.arn=arn:aws:sns:ap-southeast-1:123379395205:ClientServiceTopic.fifo

# Expose health endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true